zelytra/BetterFleet

backend/src/main/java/fr/zelytra/session/SessionSocket.java
backend/src/main/java/fr/zelytra/session/fleet/Fleet.java
backend/src/main/java/fr/zelytra/session/fleet/FleetStats.java
frontend/src/assets/locales/en.json
frontend/src/assets/locales/fr.json
frontend/src/components/fleet/FleetLobby.vue
frontend/src/objects/Fleet.ts

Modify session informations

---

frontend/src-tauri/src/window_interaction.rs

Fix focus while doing something or being on another app

---

backend/src/main/java/fr/zelytra/session/SessionSocket.java

Patch player fake banned from the server

---

backend/src/main/java/fr/zelytra/session/SessionManager.java
backend/src/main/java/fr/zelytra/session/SessionSocket.java
backend/src/main/java/fr/zelytra/session/SessionStatus.java
backend/src/main/java/fr/zelytra/session/fleet/Fleet.java
backend/src/main/java/fr/zelytra/session/player/Player.java
backend/src/main/java/fr/zelytra/session/socket/MessageType.java
backend/src/main/resources/application.properties
webapp/package.json
webapp/src-tauri/Cargo.lock
webapp/src/assets/locales/en.json
webapp/src/assets/locales/fr.json
webapp/src/objects/Fleet.ts
webapp/src/objects/Player.ts
webapp/src/objects/WebSocet.ts
webapp/src/objects/stores/UserStore.ts
webapp/src/vue/form/InputText.vue

Backend client version & Better error message

---

webapp/src/assets/icons/locales/de.svg
webapp/src/assets/icons/locales/es.svg
webapp/src/assets/locales/de.json
webapp/src/assets/locales/en.json
webapp/src/assets/locales/es.json
webapp/src/assets/locales/fr.json
webapp/src/components/Config.vue
webapp/src/main.ts

Translation update/add

---

webapp/src/assets/locales/de.json
webapp/src/assets/locales/en.json
webapp/src/assets/locales/es.json
webapp/src/assets/locales/fr.json
webapp/src/components/Config.vue
webapp/src/components/global/Header.vue
webapp/src/router/index.ts

Username length & Tooltip

---

webapp/src-tauri/src/fetch_informations.rs

We had an issue when the server was "30000" port.  Add print

Fix server port = 30000

---

webapp/src/App.vue
webapp/src/assets/locales/fr.json
webapp/src/components/Config.vue
webapp/src/components/Fleet.vue
webapp/src/components/Home.vue
webapp/src/components/fleet/FleetLobby.vue
webapp/src/components/fleet/SessionCountdown.vue
webapp/src/objects/stores/UserStore.ts
webapp/src/vue/fleet/PlayerFleet.vue

Closes #137 , #143 , #142 , #135 , #134 , #121

Webb app fixtures

---

webapp/src/components/fleet/FleetLobby.vue
webapp/src/objects/Color.ts
webapp/src/vue/templates/ServerContainer.vue

Colors for session with hash

---

webapp/src/assets/contributors/contributors.json
webapp/src/assets/locales/fr.json
webapp/src/assets/style.scss
webapp/src/components/Authentication.vue
webapp/src/components/fleet/Config.vue
webapp/src/components/fleet/session/FleetLobby.vue
webapp/src/components/fleet/session/FleetSessionChoice.vue
webapp/src/objects/fleet/Fleet.ts
webapp/src/objects/fleet/FleetTest.ts
webapp/src/vue/form/ConfirmationModal.vue

Webapp fixes

---

backend/src/main/resources/application.properties
webapp/package.json
webapp/src-tauri/Cargo.toml
webapp/src-tauri/tauri.conf.json
website/package.json

Fix version number not accurate

Post new release 0.2.1

---

backend/pom.xml
backend/src/main/java/fr/zelytra/session/SessionManager.java
backend/src/main/java/fr/zelytra/session/SessionSocket.java
backend/src/main/resources/application.properties
backend/src/test/java/fr/zelytra/session/SessionManagerTest.java
backend/src/test/java/fr/zelytra/session/SessionSocketTest.java
webapp/package-lock.json
website/package-lock.json

Ghost player espiode 2

---

backend/src/main/java/fr/zelytra/session/SessionSocket.java
backend/src/test/java/fr/zelytra/session/SessionSocketTest.java

Null username

---

.github/workflows/ci.yml
backend/src/main/java/fr/zelytra/session/SessionManager.java
backend/src/main/java/fr/zelytra/session/SessionSocket.java
backend/src/test/java/fr/zelytra/session/SessionSocketTest.java
backend/src/test/java/fr/zelytra/session/client/BetterFleetClient.java

Empty session problem

---

webapp/src-tauri/Cargo.lock
webapp/src-tauri/src/fetch_informations.rs

Patch tauri debug to info

---

website/src/assets/locales/fr.json
website/src/components/Support.vue

F.A.Q. - Frequently asked questions

---

website/src/components/global/HeaderVue.vue

Fix gray bar on website in certains conditions

---

backend/src/main/java/fr/zelytra/session/ip/ProxyCheckAPI.java

Handle possible unknown field in json from proxy checker

---

README.md
webapp/src-tauri/src/api.rs
webapp/src-tauri/src/fetch_informations.rs
webapp/src-tauri/src/main.rs

Fix server detection with multiple sockets
Little rewrite giving more readability
Optimizing logging
I'm scared of false positive but as far as I tested I didn't see any. It shouldn't be an issue, for now..
Fixes #364

Fix server detection with multiple sockets

---

backend/src/main/java/fr/zelytra/session/SessionManager.java
deployment/dev/docker-compose.yml
webapp/src/components/FleetMenuNavigator.vue

Fix server status updater

---

webapp/src/assets/locales/en.json
webapp/src/assets/locales/fr.json
website/src/assets/locales/de.json
website/src/assets/locales/en.json
website/src/assets/locales/es.json
website/src/assets/locales/fr.json

Current crowdin setup is broken and needs to be fully redone (or use weblate instead ?).
At this time a critical update is available in code but not released. 
This has been done by downloading files from crowdin and comparing versions.

Upload translations from crowdin itself

---

backend/src/main/resources/application.properties
webapp/package.json
webapp/src-tauri/Cargo.lock
webapp/src-tauri/Cargo.toml
website/package.json

Versions changes for release 1.1.0. 
Do I need to tag the commit ? to commit straight to master ?

Release 1.1.0

---

crowdin.yml
webapp/src/assets/locales/source.json
webapp/src/main.ts
webapp/src/objects/i18n/index.ts
website/src/assets/locales/source.json
website/src/main.ts
website/src/objects/i18n/index.ts
website/src/router/index.ts

Based on crowdin doc, the source file should not be the same as a translation file. fr.json is now a translation file and no longer a source file. 
Developers should now only modify source.json and the proofreading should be on crowdin side.

Trying to fix crowdin setup

---

README.md
webapp/src/assets/contributors/contributors.json

Add italian translator credits

---

README.md

Figma open source template
